services:
  postgres:
    container_name: raggae-postgres
    image: pgvector/pgvector:pg18
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: raggae
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  postgres-test:
    container_name: raggae-postgres-test
    image: pgvector/pgvector:pg18
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: raggae_test
    ports:
      - "5433:5432"
    tmpfs:
      - /var/lib/postgresql

  minio:
    container_name: raggae-minio
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data:
